import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const aribau = localFont({
  src: [
    {
      path: '/fonts/Aribau-Grotesk-Regular.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-aribau-grotesk',
  display: 'swap', // or 'block'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} 
          ${geistMono.variable}
          ${aribau.variable} 
          antialiased
        `}
        style={{ fontFamily: 'var(--font-aribau-grotesk), var(--font-geist-sans), var(--font-geist-mono), Arial, Helvetica, sans-serif' }}
      >
        {children}
      </body>
    </html>
  );
}
